# Generated by Django 2.2 on 2020-01-01 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_id', models.CharField(max_length=10)),
                ('contact_name', models.CharField(max_length=200)),
                ('contact_number', models.CharField(max_length=10)),
                ('contact_email', models.CharField(max_length=200)),
            ],
        ),
    ]
